### ISSUE TITLE
import fails in next.js

### ISSUE THREAD

**Issue by patrik-csak** [rfoel/use-prefers-color-scheme#72]
@rfoel thanks for creating this hook. it looks great and exactly what i need, but i get the following error when trying to use it in a next.js app :

```
error - pages/index.tsx (6:49) @ Home
TypeError: use_prefers_color_scheme__WEBPACK_IMPORTED_MODULE_1___default(...) is not a function
  4 | 
  5 | const Home: NextPage = () => {
> 6 |   const prefersColorScheme = usePrefersColorScheme();
    |                                                  ^
  7 |   const isDarkMode = prefersColorScheme === "dark";
  8 | 
  9 |   return (
```

i've tried importing both the default and named exports and neither way works

here's a reproduction : https://replit.com/@ptrkcsk/use-prefers-color-scheme-nextjs

**Comment by rfoel** [comment]
Hey, I've updated the build step, please try the [latest version](https://github.com/rfoel/use-prefers-color-scheme/releases/tag/v1.1.3)!

**Comment by patrik-csak** [comment]
thanks, @rfoel ! import works, but there's now a hydration error : https://replit.com/@ptrkcsk/use-prefers-color-scheme113-nextjs

i think the color scheme must be `'no-preference'` on both the first server side render and the first client side render. here's how i solved the problem using usehooks-ts : https://github.com/juliencrn/usehooks-ts/issues/84#issuecomment-1399591467

**Comment by rfoel** [comment]
@patrik-csak I have opened a separate issue for this #76. If we want to have the preffered color scheme on the first render for the cliente we have to set it as soon as possible, but it causes this error for the server side render. If I remove the changes from the version v1.1.2 it will work as expected, but then we have flash of the wrong theme.

**Comment by patrik-csak** [comment]
thanks, @rfoel
